### ISSUE TITLE
[Tutorial] In 'Step 4: Build an Element'

### ISSUE THREAD

**Issue by MechanicKim** [Polymer/docs#2166] opened 2017-05-26 08:08 UTC
In [Step 4: Build an Elemen](https://www.polymer-project.org/2.0/start/first-element/step-4)

In Safari browser, I can't see any icons
<img width="341" alt="2017-05-26 4 58 53" src="https://cloud.githubusercontent.com/assets/12149783/26486084/a7528fb2-4234-11e7-8906-e13518e6b0cc.png">
Chrome has no problem.

I confirmed javascript console and found an error.
<img width="529" alt="2017-05-26 5 00 53" src="https://cloud.githubusercontent.com/assets/12149783/26486159/ecd311e2-4234-11e7-9e68-08b261a867be.png">

(I know that addEventListener has a function as second parameter.)
I removed this line. I can see icons in Safari. However, When I clicked them, there was no change.
I confirmed that toggle event is called.

I wanna solve two things.
1. I don't know why 'this.addEventListener('tap', 'toggle');' is necessary.
2. How to solve this problem in Safari.

**Comment by MikeRankin** [comment] 2017-05-28 18:04
Confirmed in safari.  Also throws an error in Firefox: TypeError: can't assign to properties of (new String("toggle")): not an object.  In this case, the entire page fails to load.  Commenting out the addEventListener line allows the page to work in chrome and Firefox, but in safari, while the event fires and the text on the bottom item changes, the icons are not updated.

**Comment by MechanicKim** [comment] 2017-05-29 01:06
I commented out addEventListener line and edited toggle method.
```javascript
toggle() {
  this.pressed = !this.pressed;

  if (this.pressed) {
    this.style.fill = 'currentcolor';
  } else {
    this.style.fill = 'rgba(0,0,0,0)';
  }
}
```

Button works correctly in Safari!
But I think that it is not the perfect solution.

**Comment by arthurevans** [comment] 2017-06-06 23:05
You're right, the `this.addEventListener` line should be removed.

The style update in Safari turns out to be a known bug in Safari's shadow DOM implementation:

https://bugs.webkit.org/show_bug.cgi?id=170762

It's apparently fixed in WebKit nightly, but the fix hasn't rolled to stable yet.

**Closed** 2017-06-07 18:58 UTC
