### ISSUE TITLE
Polymer 2.x typescript decorators

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/docs#1787] opened 2016-10-07 03:32 UTC
Polymer typescript decorators are a whole new topic on itself, I know how to use them when they actually work but making them work seems more difficult then figuring out Donald Trump's tax returns :P 

I extraceted them out of Polymer 2.x so I could look at them separtly. When I run `tsc` I get a `decorators.js` but in the PR comments they mention that decorators.d.ts should be generated too?

For people to be able to help testing or contribute code related to polymer typescript decorators it's important we understand how this process works.

https://github.com/gertcuykens/decorators

After I do `tsc`,  should I just import that example js file in my html using a script tag? Or do I need to also include that reflect thing in my end html file?

@rictic If you have time I need help understanding how to generate decorators specificly :D

**Comment by gertcuykens** [comment] 2016-10-07 05:03
Aaa I am slowy beging to understand I think, I am going to need that webpack crap don't I when I want to use decorators...

**Comment by gertcuykens** [comment] 2016-10-07 06:29
I am stuck, webpack doesn't bundle the code :( need help

https://github.com/gertcuykens/decorators

**Comment by daflair** [comment] 2016-10-22 12:41
I've played around a little with Polymer 2 and Typescript, here are some observations, maybe we can try to figure things out together! I am concerned that there seems to be too much emphasis on not falling into the same problems that ng2 did, leading to new and unarticulated problems.

I'm not into relying too much on webpack myself, so I followed an early-bound transpilation approach. Here is a gist: [Polymer 2 / TypeScript (using 2.0-preview branches)](https://gist.github.com/daflair/05889c2cd0f44cbd4314bf4703d27bcc)

I am getting all of the cool features but staying away from any thing gained from relying on modules / loaders. I'm also not using the ts files in production, they are simply development files that transpile on save and Polymer works with js files without special workarounds.

Let me know what your thoughts are!

**Comment by gertcuykens** [comment] 2016-10-22 13:53
Ok thanks, cloning your files and trying it out. Note that rictic also is going to make the decorator thing more clear as soon he doesn't have a jet lag anymore.

Maybe also take a look on this PR https://github.com/Polymer/polymer/pull/3954 and submit comments if you have TS improvements.

**Comment by daflair** [comment] 2016-10-22 17:02
Yeah, I've seen this PR, if only we can figure out the transpilation scenario where Polymer and TypeScript would be compatible, bridging some transpiled module mode from TypeScript to some form of Polymer supported loader. So far, I think TypeScript is a tangent, that can be AnyScript as far as Polymer is concerned :(

I'm still working my through the decorators though but the most essential one @property() seems to work demodularized when loaded as a transpiled in a script/javascript tag inside a link/import at the top of the custom element's html file.

**Comment by gertcuykens** [comment] 2016-10-24 15:34
I went through your gist but there are many other steps required to show case your demo, I suggest to make it a separate repo that includes for example bower.json .gitignore and the types directorie etcetera. Thanks

**Comment by daflair** [comment] 2016-10-25 18:25
Yeah… will do first thing in the am!

Saleh Abdel Motaal

**Comment by daflair** [comment] 2016-11-04 19:03
@gertcuykens 
So... AM is ~ 10 days in my world apparently :)

But, I've been super busy trying to figure things out and I have a custom element sample project, which includes a sample wrapped library (as a subtree), all created in TypeScript, with updates to the index.html files created by the polymer-cli and the bower/package.json dependencies to use the 2.0-preview branches. I am honestly new to Polymer and was catching up to their very unique underlaying philosophy.

Check out the [sample repository](https://github.com/PolyNerds/color-molecule-elements/) which includes a fairly detailed README that describes in detail the setup and decisions made to get there.

So far, I've only gotten to the point where I have a solid TypeScript/Polymer integration for creating the element and working with a TypeScript-based package as a dependency but still nothing on testing & building!

**Comment by gertcuykens** [comment] 2016-11-08 22:26
I looked at it and my conclusion is that I probably wait for es6 modules to be supported in browsers before using decorators. I want to output es6 so that the transpiled code itself looks almost identical to ts code but just without types.

**Comment by daflair** [comment] 2016-11-09 11:40
I hear you... Although I'm confident that on the long-term Polymer has a much more solid outlook, everything else around it is in a very different world right now. I'm guessing that unlike classes/functions which can be redefined within scopes, custom elements cannot be redefined, so when everybody who is Javascript is hard-set on using modules and scopes (necessary) it seems that custom elements (residing in both the script-like-module world and the dom-like-script world) are not easily lending themselves nicely across the two paradigms.

If what you are really looking for is ES6 down the road, try the popular (I'm not sold) workflow of TypeScript>Babel>Polyfills, but this means your code will likely become anything but ES6 until eventually when we are in the "true" year of "ES2015"

**Comment by gertcuykens** [comment] 2016-11-09 17:38
My work flow is tsc and that's it :) as long as I avoid decorators it's working fine https://github.com/gertcuykens/hello-world and if I can get this trough https://github.com/Microsoft/vscode/issues/14032 I don't even have to bother with getting the ts code out of the components

**Comment by gertcuykens** [comment] 2016-11-13 02:22
Finally I got something working thx to your example... now the only thing left is to figure out polymer imd vs umd.

Tried imd but that doesn't do much in my example...

https://github.com/gertcuykens/decorators

**Comment by daflair** [comment] 2016-11-13 13:20
Polymer IMD is simply a wrapper for AMD's method of writing modules: `define('#module-id', ['#dep1-id' ...], function (Dep1, ...) {}` 

To use them, you need to switch to AMD in `tsconfig.json`, but also, since IMD does not load modules, you need to load your scripts with `<script>` tags where you first load IMD (index.html works best), then you load dependencies (link import with script tags are ideal), then you load your module.

A neat trick in TS is that you you can use triple-slash directives to specify exactly how the amd calls are written: [Look for amd stuff here!](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html), which describes how you can define module ids and specify dependency paths

This trick should help you with the obvious pain point of figuring out how the heck to use `import from 'module'` statements in the TypeScript world that would translate to `define(['path/module.js'], ...)` in JS... I can help there if you run into trouble!

One problem you will sometimes run into is libraries, like `marked.js`, which I guessed (never got around to confirm) uses something like UMD to poly-morphically load depending on the environment it loads in, and that means IMD makes them behave different, and Polymer's molecule will crash if it does not expect the marked.js as an AMD module. The short solution is to load all such dependencies before IMD in your index.html.

These are some of the observations so far.

**Comment by gertcuykens** [comment] 2016-11-14 02:34
Got it working your way using amd, and on chrome it works perfect but on safari 10 webcomponents.js#v1 polyfil doesn't have a working html imports.

https://github.com/gertcuykens/decorators

**Comment by daflair** [comment] 2016-11-14 10:54
I'm still using   `../webcomponentsjs/webcomponents-lite.js`

**Comment by gertcuykens** [comment] 2016-11-14 19:31
I was wrong, it's more complicated then I thought. Seems like the order of scripts and imports in index.html need to be in such a way that Safari doesn't rearrange it the wrong way when executing the polyfills... Polymer dom does that for you but when you want to do it manually your in for a surprise on other browsers grrrr

Browser vendors my ass that they are ready for web components...

**Comment by daflair** [comment] 2016-11-14 21:49
Oh… that's why I created a separate feature pull-request (no replies) with IMD for AsyncPromesis.

Basically to overcome this problem, I implemented a Promises-based registry on top of IMD which did all the necessary defers until dependencies are loaded. So regardless of sequence of tags, as long as all scripts are included, dependencies resolve hierarchically.

https://github.com/daflair/IMD/tree/feature/AsyncPromises

**Comment by daflair** [comment] 2016-11-14 21:55
I think the excitement was misleading, but if you really listen to what the Polymer team was really saying, they are happy because after 3 years in the gray, web components is actually v1, which means it is something all browsers want to adopt, and are in agreement on the specs… the did not really mean that Polymer runs native, but then again, usetheplatform was misleading, it is meant to take the spotlight away from native Apps!

**Comment by daflair** [comment] 2016-11-17 12:20
By the way Safari TP now has full support for Shadow and Custom Elements, not sure what roadmap looks like for public release!

**Comment by gertcuykens** [comment] 2016-11-17 13:40
Nice :) But Edge and FireFox don't do css `:host` for example https://jsbin.com/quvozo so if each browser has a slightly different shadow dom interpretation then its going to be an even bigger mess...

**Comment by daflair** [comment] 2017-02-19 00:01
@gertcuykens I know this is an old thread... but the issue is still important, and I have an update :)

https://gist.github.com/daflair/ccaf74520480cfb8f7979e337d905f3f

**Comment by arthurevans** [comment] 2017-10-02 23:06
We'll document typescript decorators when there are official typescript decorators shipped with the library. In the mean time, I'm closing this issue (since it's not really docs-related and I believe there are typescript-related discussions elsewhere).

**Closed by arthurevans** 2017-10-02 23:06 UTC
