### ISSUE TITLE
When possible, replace examples with live examples + add "Edit in Plunker" links

### ISSUE THREAD

**Issue by steren** [Polymer/docs#868] opened 2015-01-10 19:34 UTC
On the page https://www.polymer-project.org/docs/polymer/binding-types.html and https://www.polymer-project.org/docs/polymer/databinding-advanced.html, I would expect to be able to see real live examples of the explained concepts, not only code snippets.

For example, I am locally playing with binding outside of polymer elements, and have issues. I would like to quickly fork the [given example](https://www.polymer-project.org/docs/polymer/databinding-advanced.html#bindingoutside) in plunker to perform some quick tests.

**Comment by addyosmani** [comment] 2015-01-11 00:29
We've talked about doing something like this before with Plunker or JSBin. cc @robdodson @ebidel

**Comment by robdodson** [comment] 2015-01-12 21:39
@tjsavage this might be a good sprint goal

**Comment by ebidel** [comment] 2015-04-06 16:51
Dupe of #830

**Closed** 2015-04-06 16:52 UTC
Labels: duplicate
