### ISSUE TITLE
polymer-project.org navigation fails in Firefox

### ISSUE THREAD

**Issue by kito99** [Polymer/docs#2468] opened 2018-02-07 18:13 UTC
Environment: Firefox 58.01 on macOS High Sierra

Behavior: Clicking on the navigation for the site has no visible effect.

Console output:

![2018-02-07_13-12-15](https://user-images.githubusercontent.com/3187538/35933456-b8954ba4-0c08-11e8-8ff4-588ed372a0f7.png)

**Comment by katejeffreys** [comment] 2018-02-07 19:57
I haven't been able to reproduce this yet, but participants in this thread https://github.com/home-assistant/home-assistant-polymer/issues/428 report a similar error and connected it with the LastPass extension. I'm going to install that extension in Firefox now and see what happens.

**Comment by kito99** [comment] 2018-02-07 20:08
Good find... I just disabled the plugin, refreshed the page, and things started working fine. When I enabled the plugin again, they worked fine until I refreshed the page. 

I've been using that plugin for years and this is the first time I have seen it cause a problem. I have it installed in both Chrome and Safari as well, and neither of them have a problem with the site, so there is definitely something specific to Firefox here.

**Comment by katejeffreys** [comment] 2018-02-07 20:10
I reproduced the error with the LastPass extension.

Also found this https://github.com/PolymerElements/iron-icon/issues/109 which connects a similar error with webcomponentsjs v 1.0.5 in Firefox. I will dig in a bit further...

**Comment by katejeffreys** [comment] 2018-02-07 21:16
Here is the issue that will (hopefully?) fix it: https://github.com/webcomponents/custom-elements/pull/138

Going to close this.

Incidentally, Firefox nightly doesn't have this issue because it doesn't use the polyfill. So that's something...

**Closed** 2018-02-07 22:20 UTC
