### ISSUE TITLE
Script 404 Not Found?

### ISSUE THREAD

**Issue by ArianeLu** [Polymer/docs#1468] opened 2015-12-14 02:42 UTC
1.Open https://www.polymer-project.org/1.0/docs/start/quick-tour.html
2.Open F12(DevTools),Check 'Console' Tab

Error:
GET https://www.polymer-project.org/1.0/samples/components/webcomponentsjs/webcomponents-lite.js 404 (OK)

Uncaught ReferenceError: Polymer is not defined

**Comment by ebidel** [comment] 2015-12-14 05:33
@arthurevans the demos on that page are no longer working.

**Comment by arthurevans** [comment] 2015-12-14 07:42
Wrong version may be live. My PR should fix this. Will check it out tomorrow AM.

**Comment by arthurevans** [comment] 2015-12-14 07:51
OK, swapped to the new version with my PR in place because it appeared to be less broken. Demos all seem to be working now. Please let us know if you see any more problems.

**Comment by arthurevans** [comment] 2015-12-14 19:23
Specifically, this should be fixed by #1466, which is now live.

Caused by my prematurely deploying the commits with the API doc changes in them.

**Closed** 2016-01-15 00:18 UTC
Labels: P0
