### ISSUE TITLE
[new site] make sure "Edit on Github" buttons point to the right repo

### ISSUE THREAD

**Issue by tjsavage** [Polymer/docs#1630] opened 2016-05-26 16:15 UTC

**Comment by tjsavage** [comment] 2016-05-26 16:15
This won't be relevant until the repo for the new site is moved over to here.

**Comment by notwaldorf** [comment] 2016-05-26 23:43
closing as duplicate of https://github.com/Polymer/docs/issues/1622

**Closed by notwaldorf** 2016-05-26 23:43 UTC
