### ISSUE TITLE
Bizarre web page behavior

### ISSUE THREAD

**Issue by kirbyfan64** [Polymer/docs#1551] opened 2016-02-22 17:53 UTC
This was interesting...I'm not sure where to report this, so I'm guessing it's here.

I went over to the [`paper-icon-button` docs](https://elements.polymer-project.org/elements/paper-icon-button). When I clicked the `iron-iconset` link, it simply redirected me to a non-existent anchor on the same page.

When I hit the button on the left to go back to the list of paper elements, I noticed that the title of the Chrome tab was still `paper-icon-button`, even though I was in the list of elements.

Then I went to the [`iron-icon` docs](https://elements.polymer-project.org/elements/iron-icon). The demo page says:

> **This demo is for a single \<iron-icon>. If you're looking for the whole set of available icons, check out the [\<iron-icons> demo.](https://elements.polymer-project.org/elements/iron-icons?view=demo:demo/index.html)**

So I clicked the link. And this is what I saw:

![iron-icon - polymer element catalog - google chrome_001](https://cloud.githubusercontent.com/assets/1690697/13227142/c864180e-d95a-11e5-8847-bca8d7bca472.png)

Uhhh....

**Comment by arthurevans** [comment] 2016-02-23 22:00
I think this may be a duplicate of https://github.com/Polymer/polymer-element-catalog/issues/237.

**Comment by kirbyfan64** [comment] 2016-02-23 22:09
For the last part of the issue. The first part of it separate.

**Comment by arthurevans** [comment] 2016-02-23 22:41
Yep. Bad link I can fix.

This part I can't repro: 

> When I hit the button on the left to go back to the list of paper elements, I noticed that the title of the  Chrome tab was still paper-icon-button, even though I was in the list of elements.

Last part is definitely a bug in the catalog.

**Comment by arthurevans** [comment] 2016-03-05 22:17
OK, bad link is fixed in the source, will be fixed as soon as we re-release paper-icon-button and update the catalog.

Can't replicate the incorrect title issue and the duplicate left nav entry is already reported on the catalog repo, so I'm going to close this issue now.

If you see the incorrect title on the catalog again, please open a ticket with reproduction steps. Thanks!

**Closed** 2016-03-05 22:18 UTC
Labels: bug, P1
