### ISSUE TITLE
Extracted documents for Polymer proper are not directly linkable

### ISSUE THREAD

**Issue by ktiedt** [Polymer/docs#1352] opened 2015-09-14 04:40 UTC
If you try to refer anyone to the docs for Polymer proper features here: http://polymer.github.io/polymer/ you cannot link directly to say... dom-repeat or dom-bind pages there... it is a very different L&F from all the other doc pages that are referenced quite often for support issues.

**Comment by arthurevans** [comment] 2015-09-16 17:31
I think this is a duplicate of: https://github.com/PolymerElements/iron-doc-viewer/issues/53

**Closed by arthurevans** 2015-09-16 17:31 UTC
