### ISSUE TITLE
dev_appserver.py: command not found

### ISSUE THREAD

**Issue by rhedin** [Polymer/docs#1855] opened 2017-01-05 12:23 UTC
Hello.  I followed the instructions, and when I got to:  ```dev_appserver.py dist/``` I got the above message. 

I am working on a Macintosh.  Running El Capitan.

I haven't encountered App Engine before.  Does it come with a Mac?  Do I need to install it?  

Regards, Rick

**Comment by rhedin** [comment] 2017-01-05 18:56
Okay, I installed Google Cloud SDK from here.  

https://cloud.google.com/appengine/docs/python/tools/using-local-server

When I ran it though, it gave this complaint. 

google.appengine.tools.devappserver2.errors.AppConfigNotFoundError: "dist/" is a directory but does not contain app.yaml or app.yml

Which is perfectly true.  app.yaml is at the top level, not in the dist/ directory.

**Comment by rhedin** [comment] 2017-01-05 19:00
Arghh.  And when I run it without referring to dist -- 

./dev_appserver.py . 

and go to localhost:8080, I get this -- 

`Internal Server Error

The server has either erred or is incapable of performing the requested operation.

Traceback (most recent call last):
  File "/Users/rickhedin/work/170105/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Users/rickhedin/work/170105/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1595, in handle_exception
    return handler(request, response, e)
TypeError: handle_500() takes exactly 4 arguments (3 given)`

**Comment by arthurevans** [comment] 2017-01-20 23:11
OK, it sounds like your build isn't complete (the build should copy app.yaml into the dist folder). Did the gulp command throw any errors?

Make sure you have all of the npm modules installed (you can re-run the npm install command and see if it complains about anything) and that you ran the original clone with the `--recursive` option.

**Comment by arthurevans** [comment] 2017-02-10 23:42
We've fixed one issue with the build (a bad dependency). Can you try updating your local repo, and rerunning the `bower install` and `gulp` steps?

**Comment by montrealist** [comment] 2017-02-27 20:54
Had a similar issue. Worked fine for me after installing Google Cloud SDK (steps 1-4) from here:

https://cloud.google.com/sdk/docs/

**Comment by katejeffreys** [comment] 2017-04-07 02:44
AFAIK fixing the bad dependency has resolved this issue. I am going to close this but feel free to re-open if the issue is not addressed. Thanks everyone.

**Closed by katejeffreys** 2017-04-07 02:44 UTC
