### ISSUE TITLE
Strange lines on polymer site menu

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#1109] opened 2015-05-31 02:37 UTC
_From @oswaldomilet on May 30, 2015 1:10_

Happens on Safari 8.0.6 after expand "Local DOM" for example

![captura de tela 2015-05-29 as 22 07 06](https://cloud.githubusercontent.com/assets/10772835/7895020/4760e978-064f-11e5-90e2-b5df51a32ace.png)

_Copied from original issue: Polymer/polymer#1675_

**Comment by manonthemat** [comment] 2015-08-23 22:01
Can not replicate this on Safari 8.0.8

**Comment by arthurevans** [comment] 2015-11-06 19:44
Also cannot reproduce. Closing.

**Closed by arthurevans** 2015-11-06 19:44 UTC
