### ISSUE TITLE
 Polymer website docs not rendering in Firefox 54.0

### ISSUE THREAD

**Issue by teoincontatto** [Polymer/docs#2259] opened 2017-07-19 13:10 UTC
When opening a link to a Polymer website docs page the page does not render. For example page https://www.polymer-project.org/2.0/start/quick-tour is rendered correctly following links from main page but after reloading the page does not render. The following error is emitted in console:

    SyntaxError: ':not([style-scope]):not(.style-scope):host,html:not([style-scope]):not(.style-scope)' is not a valid selector pw-shell.html-2.js:1

![screenshot from 2017-07-19 15-11-26](https://user-images.githubusercontent.com/3866849/28368492-c52d1658-6c94-11e7-9e3b-390b466b346f.png)

**Comment by web-padawan** [comment] 2017-07-19 14:42
A duplicate of #2258

**Closed** 2017-07-20 19:56 UTC
