### ISSUE TITLE
Polymer in 10 minutes - switching tabs in examples breaks scrolling

### ISSUE THREAD

**Issue by laserpanda** [Polymer/docs#1030] opened 2015-04-25 20:11 UTC
I go to this page using latest (42) chrome on win64:

https://www.polymer-project.org/0.5/docs/start/creatingelements.html

Go down to any of the example bits where you can see the code in action, such as proto-element.html, then switch over to the index.html tab and then back to the proto-element.html tab. now the horizontal scroll bar has stopped working.

**Comment by arthurevans** [comment] 2015-05-05 00:51
Hoping @ebidel or @robdodson can exercise their web-fu on this one.

**Comment by robdodson** [comment] 2015-05-07 14:28
I'm on a mac so maybe this is the issue.. are you clicking to drag the
scrollbar or using a scroll device? I'm curious if this is a Chrome bug

**Comment by derpDiggler** [comment] 2015-05-07 14:51
i used a wacom pen, but now tried with a mouse to drag the scrollbar and have the same problem. The arrows dont work either.

What I just noticed is that when I switch tabs it resizes, and when it switches/resizes back to the first tab the scroll bar appears UNDER the textarea, not inside it as originally. (see screenshot)

![image](https://cloud.githubusercontent.com/assets/5430523/7518113/ef3d7606-f4d0-11e4-9334-2be350a60313.png)

**Comment by robdodson** [comment] 2015-05-07 19:24
Yeah my gut says this is a Chrome bug with Windows and Shadow DOM because I
think I've seen it before. Now the only tricky bit is coming up with a
reduced test case so it can be reported... :\

@arthure if you're in SF today do you think you could show this to a member
of the Polymer team to see what they think? Maybe we can grab a blink eng
and get them to take a look

**Comment by arthurevans** [comment] 2015-05-08 16:04
So I showed this to Frankie & he found that we have `overflow-x: auto` on all the `<pre>` elements to allow folks to scroll them on narrow screens. If we take that *off*, the element scrolls properly (but it looks weird -- the background color ends where the code was originally cut off by the edge of the element).

Frankie also noted that setting the `<pre>` to `overflow-x: true` was a little funky and you'd normally do that on a parent element. I think we use it so that our regular inline code samples scroll on a narrow screen.

It's probably some kind of Chrome-on-windows bug, but it's sort of a corner case and therefore likely to be both hard to isolate and low-priority to fix, so we should probably figure out a workaround.

At Frankie's suggestion, I tried setting the overflow-x: auto on a parent element instead, setting background on a parent element, and several other variations, but I was unable to find a combination that worked.

**Comment by robdodson** [comment] 2015-05-08 16:20
hm ok I can take a stab at it....after I write some I/O talks :P

**Comment by dyoo** [comment] 2015-10-21 01:24
I can reproduce this situation in Chrome 46.0.2490.71 m.  I'm running on Windows 10, using a mouse as my scrolling device.

**Comment by katejeffreys** [comment] 2017-02-17 22:25
This is no longer a thing. Closing.

**Closed** 2017-06-14 19:48 UTC
