### ISSUE TITLE
docs/app/2.0/toolbox/build-for-production.md review

### ISSUE THREAD

**Issue by ensonic** [Polymer/docs#2277] opened 2017-08-02 11:37 UTC
Send https://github.com/Polymer/docs/pull/2276 for some obvious fixes. There a re a few more things that I am happy to fix if you someone helps to answer my quations:

https://www.polymer-project.org/2.0/toolbox/build-for-production#why-do-we-need-a-build-process
"The Polymer build tools can handle this requirement by splitting inline JavaScript and CSS from HTML." this should link to a section that describes how to do this. Polymer 1.x docs recommended crisper, is this still the way to do it?

**Comment by katejeffreys** [comment] 2017-08-02 18:13
See #2101

**Comment by katejeffreys** [comment] 2017-08-10 22:39
Closing as duplicate of #2101

**Closed by katejeffreys** 2017-08-10 22:39 UTC
