### ISSUE TITLE
Radio buttons are not being displayed correctly in Safari

### ISSUE THREAD

**Issue by benediktr** [Polymer/docs#1250] opened 2015-07-07 07:20 UTC
The bullets are not positioned correctly within the circles.

<img width="346" alt="screen shot 2015-07-07 at 09 20 09" src="https://cloud.githubusercontent.com/assets/234840/8540824/612ef856-2489-11e5-9480-035f926c263b.png">

Safari 8.0.6 (10600.6.3)
OS X Yosemite 10.10.3

**Comment by robdodson** [comment] 2015-07-07 18:13
Hm, I wonder if this is still an issue with the 1.0 version.

@benediktr can you take a look at [this page](https://elements.polymer-project.org/elements/paper-radio-group?view=demo:demo/index.html) and let me know if they look better

**Comment by ebidel** [comment] 2015-07-07 18:28
Dupe of https://github.com/PolymerElements/paper-radio-button

**Closed by ebidel** 2015-07-07 18:28 UTC

**Comment by robdodson** [comment] 2015-07-07 18:31
https://github.com/PolymerElements/paper-radio-button/issues/38

**Comment by ebidel** [comment] 2015-07-07 18:35
Oops. Left out the issue # :)
