### ISSUE TITLE
confusion around observers of undefined properties

### ISSUE THREAD

**Issue by mgiuffrida** [Polymer/docs#1419] opened 2015-11-09 23:58 UTC
The "Declared properties" page (`docs/devguide/properties.md`) talks about observing undefined properties but doesn't really specify all the behavior I'm seeing.

According to the docs:
- Observers are not invoked until all dependent properties are defined (!== undefined).

This implies that single-property observers defined on individual properties are invoked even when they are initially undefined, but that is false.

It also leaves open the question of whether single-property observers are invoked when the sole dependent property is undefined. It seems they are not invoked if the property is undefined, but if the dependent property is a path, they are invoked if the base property is defined, even if the value at the path is undefined. So a clarification there would be helpful.

**Comment by arthurevans** [comment] 2015-11-10 00:18
Hmm... I think @sorvell and/or @kevinpschaaf recently made some changes in the handling of undefined values, but I'm not sure wether they affect observers. 

The property vs. path behavior you describe sounds confusing, and perhaps a bug. I appeal to the above worthies for clarification.

**Comment by kevinpschaaf** [comment] 2015-11-17 01:10
The general rules are as follows:

Single-property/path observers:

* Called when the property (or root property if a path) becomes defined (`!==undefined`)
* Called for _every_ change of the property thereof including changing back to `undefined`

Multi-property/path observers:

* Called when all dependent properties/paths become defined (`!==undefined`)
* Called for _every_ change to any dependent property as long as all properties/paths remained defined

This comment adds some more color to the rules: https://github.com/Polymer/polymer/issues/2158#issuecomment-127428602

However, note a couple of known issues affecting the rules above:

* https://github.com/Polymer/polymer/issues/2360 - `undefined` values are not consistently prevented from entering the configuration process
* https://github.com/Polymer/polymer/issues/2158 - Computed binding not executed if argument is undefined - Although this is marked as "by design", it practically results in the inability to use multi-property observers/computed functions if one of the arguments is a path that may become undefined
* https://github.com/Polymer/polymer/issues/2749 - Observer with single path argument called for multiple variations of "undefined"

**Comment by katejeffreys** [comment] 2017-07-28 01:30
To help with prioritization and managing workload, I will close this issue with no docs changes in 7 days. To prevent that from happening, please comment within 7 days. Thanks!

**Comment by arthurevans** [comment] 2017-07-28 06:26
I think this behavior is clearer in the 1.x docs now, and the 2.x behavior is different (and also documented). Think we can close this.

**Closed by arthurevans** 2017-07-28 06:26 UTC
Labels: enhancement
