### ISSUE TITLE
SEO for Polymer docs are pretty bad

### ISSUE THREAD

**Issue by davenotik** [Polymer/docs#940] opened 2015-03-10 23:19 UTC
The biggest issue is that it's hard to get to the specific element's page. This should be at the top of search results for specific queries. That it's not wastes seconds each time as I go to the core elements page and hunt through the menus, and it adds up and becomes frustrating. (Ironically, the issue seems to be SPAs such as with Polymer in general.)

Example:

Query: `core-header-panel polymer`
https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#qscrl=1&q=core-header-panel+polymer

Expected: direct link to: https://www.polymer-project.org/0.5/docs/elements/core-header-panel.html

Related, the top link there is broken: https://www.polymer-project.org/components/core-header-panel/demo.html

**Comment by ebidel** [comment] 2015-03-10 23:31
We updated URLs yesterday so it's going to take a while for Google Search to re-index the new versioned URLs.

@robdodson also added static pages for element documentation as part of that push. This will hopefully make things a lot better when searching for elements!

**Comment by davenotik** [comment] 2015-03-10 23:46
Glad to hear! Re: providing static pages alongside the SPA, can you point to that code so I can learn from the practice?

**Comment by ebidel** [comment] 2015-03-10 23:49
Rob created a node script that generates static files from polymer element documentation. This means it can still be used dynamically at runtime, but you want static docs...boom!

https://github.com/robdodson/doc-merge

https://github.com/Polymer/docs/blob/master/_plugins/element_pages.rb is the jekyll bit.

**Comment by salamanders** [comment] 2015-03-11 17:51
+1 https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=polymer%20button first hit is broken.

**Comment by davenotik** [comment] 2015-03-11 18:00
Yea, got to add a 0.5 now, as per yesterday's blog post: https://blog.polymer-project.org/updates/2015/03/10/updated-site/

So: https://www.polymer-project.org/0.5/components/paper-button/demo.html

**Comment by ebidel** [comment] 2015-03-11 18:15
Search is smart. Give it some time to recrawl :) We submitted links yesterday to speed up the process.

**Comment by salamanders** [comment] 2015-03-15 02:40
yay crawling (first hit fixed now.)  Yay me happening to run into this in the small window when it was broken - and it not being a long term issue.  :)

**Comment by matteocrippa** [comment] 2015-03-17 22:10
little OT, but it could be partially related: anyone tried to manage a SEO test case with a dynamic website developed in polymer against a static one? how google bot manage to render a page due to high use of js?

**Comment by davenotik** [comment] 2015-03-17 23:46
It's certainly related, but not the point of this thread. The documentation for each individual element never  got indexed as a direct link in search results due to how Polymer sites are JS heavy SPAs (single page apps). @ebidel mentioned they were serving static files for SEO purposes, though it doesn't seem Google results have been updated/improved based on that yet. The broader discussion of SEO with Polymer and SEOs is for another thread.

**Comment by robdodson** [comment] 2015-03-18 01:05
>
> The documentation for each individual element never got indexed as a
> direct link in search results due to how Polymer sites are JS heavy SPAs
> (single page apps)


I think, more specifically, it was because we were using a mixed up hash
identifier. Our pages would end in core-elements.html#core-ajax, whereas
the Google recommended approach is to use #! as your fragment identifier.
I'm not sure if including .html followed by the hash was causing things to
be worse.


> though it doesn't seem Google results have been updated/improved based on
> that yet


The static files are now (slowly) starting to show up for me in search.
Google "core-ajax" and it'll should be around the 6th result down the page.

**Comment by ebidel** [comment] 2015-04-06 16:40
can we mark this closed? I see elements in the search results with the new site update

**Comment by davenotik** [comment] 2015-04-06 16:50
I see this as an issue still.

"core-input polymer": http://d.pr/i/18jrw
"core-animation polymer": http://d.pr/i/NKuk

It's a big deal in many of us are often looking up the docs for individual elements, and it's hard to get at them still. Would a sitemap help?

**Comment by arthurevans** [comment] 2015-04-06 17:20
I don't think a sitemap is going to help at this point. The sitemap helps ensure that pages get _crawled_, but it doesn't (as I understand) do anything to boost the ranking.

If you do a search for core-input on the Polymer site, you'll get the right page (although even here, it's ranked 4th, which obviously could be better):

https://www.google.com/search?q=site:polymer-project.org+core-input

So with Rob's recent fixes, all of the API doc pages are getting crawled and indexed, which was NOT happening for most of them before we changed the doc URLS. (Incidentally, from an SEO point of view, it appears that the problem wasn't that the pages were JavaScript heavy, but because we used hashes in the URLs. Now each API page has its own URL, which makes the crawler much happier.)

We still have a problem with ranking, and I think that's especially bad with short pages like core-input, where there doesn't seem to be (from the crawler's point of view) much unique content.

After doing some analysis, it appears that one problem here may be that all of the Core elements, for example, are served with the same title -- Polymer core elements -- rather than a unique one, like "core-input." This is one of the things that the crawler uses to determine whether the page is relevant, and we're missing here.

I made some tweaks in Webmaster Tools last week, but I don't expect dramatic results from them. I'm going to assign this to Rob to see about getting titles and keywords set correctly on the reference pages.

(From an SEO point of view, I think the main takeaway so far is that what matters for Polymer apps is the same as any other apps.)

**Comment by arthurevans** [comment] 2015-04-06 17:21
@robdodson See above comment -- hoping you can take a look at this.

**Comment by robdodson** [comment] 2015-04-06 17:30
yep i'll take a look today

**Comment by arthurevans** [comment] 2015-04-21 21:52
Rob's title fix has made significant improvements now that the indexer has had a while to chew on the updated pages. 

"element-name polymer" does pretty well for almost all of the elements that I've tried (where "pretty well" is a spot in the top 3 results).  "element-name polymer core elements" or "element-name polymer paper-elements" does even better -- usually 1st result. 

For some reason, core-animation is still holding out on us. I submitted this to the crawler on webmaster tools last week, so hopefully that will improve, too.

If you get bad results for any of the other elements, please post it here and I'll try to get it recrawled.

**Comment by arthurevans** [comment] 2015-09-18 01:01
Closing this as the 0.5 element docs aren't being indexed any more. The element catalog seems to be indexing OK.

**Closed** 2015-09-18 01:04 UTC
Labels: elements

**Comment by oneezy** [comment] 2016-04-22 11:49
Re-visiting this @arthurevans  and @robdodson , I'm feeling pretty confident on what I've read here about Polymers SEO. Is there an updated thread or link you guys can point me towards that goes a bit more in depth w/ proper SEO handling for Polymer or is this all included in the Polymer Starter Kit? (Sorry, I'm just starting to get my feet wet)

**Comment by robdodson** [comment] 2016-04-22 14:34
@oneezy The SEO for Polymer shouldn't be different from any other pages. Our understanding is that web components shouldn't affect search and according to the [web masters blog](https://webmasters.googleblog.com/2014/05/understanding-web-pages-better.html) the crawler does spend some time running javascript against a page so it should be able to crawl your elements after they boot up. The best example I can point folks to is our catalog. Search `polymer iron-ajax` and you'll get a result in elements.polymer-project.org. That entire site is one big element.

**Comment by Yuen92** [comment] 2017-07-14 13:39
@robdodson It seems with the num Polymer-CLI all starter-kit doesn't render in Google Search Console "Fetch as Google" : 
polymer-2-application
polymer-2-starter-kit
shop

We can also get the same behaviors with Google Page Speed Insights: 
https://developers.google.com/speed/pagespeed/insights/?hl=fr&url=https%3A%2F%2Fshop-init.appspot.com%2F&tab=desktop

Whereas your demo render well : 
https://developers.google.com/speed/pagespeed/insights/?hl=fr&url=https%3A%2F%2Fshop.polymer-project.org%2F&tab=desktop

I will continue to investigate but it will be great if Google Search Console can provide some console.log.

Thanks

**Comment by robdodson** [comment] 2017-07-25 05:28
I'm looking into this. I've got some questions for folks on the team but everyone is asleep right now so i'll try to follow up tomorrow :)

**Comment by TBLOREAL** [comment] 2017-07-27 12:44
@robdodson : 
Thanks you

I investigate a bit more and I saw 2 thing when I look google app engine log.
Google Bot doesn't request "/src/shop-home.html" file.
For Google Page Speed Insight uses Chrome 41 which doesn't request "/src/shop-home.html" file too.

I will try to install Chrome 41 in order to what's the error. I hope I will be able to do it this week-end.
Thanks

Yuen92/TBLOREAL

**Comment by marcelofranzen** [comment] 2017-07-31 15:49
Hello, there is some news about @Yuen92 's  issue? I have the exactly same problem.

https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Falbion.oaktavern.cc%2F&tab=mobile

**Comment by TBLOREAL** [comment] 2017-07-31 16:11
@marcelofranzen : 
Hi, no sorry I get some trouble to install Chrome 41. I don't find a way to do it. I didn't find a Chrome 41 portable in order to test the behavior.

I took a look on your website and it seems you don't use Polymer 2.X but Polymer 1.X.
So I think we have the same problem and it doesn't come from the Polymer version.
Maybe it's the problem comes from "webcomponentsjs/webcomponents-loader.js" version. But without any log or error it's a bit hard.

@robdodson : 
Did you get some answers from the team?

Thanks

**Comment by marcelofranzen** [comment] 2017-07-31 16:43
@TBLOREAL  , some components are 1.X, but the project core are 2.X.
I guess will be hard find a Chrome 41, could Chromium 41 help?

https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win/306748/

**Comment by marcelofranzen** [comment] 2017-07-31 18:29
@TBLOREAL  after some tiers and a lot of coffee, we was capible to solve the problem, at least for us. We just change from ES6 to ES5, apparently GoogleBot can't handdle ES6 yet.

I hope it work out for you too.
Cheers!

**Comment by Yuen92** [comment] 2017-07-31 22:14
@marcelofranzen : 
What kind of build did you use?
I still have the problem with the preset "es5-bundled". Google bot doesn't request "custom-elements-es5-adapter.js"

**Comment by marcelofranzen** [comment] 2017-08-01 05:01
@Yuen92 our build parameters are very simples: --preset es5-bundled --name oaktavern.

**Comment by robdodson** [comment] 2017-08-04 03:11
yeah I think you'll have to use the es5 version for the google crawler to pick it up

**Comment by TBLOREAL** [comment] 2017-08-08 09:40
@marcelofranzen & @robdodson  : 
The problem is solved using : 
- ES5 build
- custom-elements version 1.0.5 : https://github.com/webcomponents/custom-elements/pull/107
- load element after polyfill : https://github.com/Polymer/shop/pull/140

Thank you, you 2.

**NB :** 
See also : 
- https://github.com/Polymer/shop/issues/135#issuecomment-320903983

**Comment by marcelofranzen** [comment] 2017-08-08 10:39
@TBLOREAL Nice, you solve it. Thanks for share the solution, certainly will help other people with the same problem. By the way, Google, slowly, started indexing our links. Was a relief when I saw the first 3 links indexed.

I wish you success in your project.
