### ISSUE TITLE
Missing doc for iron-flex-layout

### ISSUE THREAD

**Issue by devmao** [Polymer/docs#1118] opened 2015-06-01 14:30 UTC
https://elements.polymer-project.org/elements/iron-flex-layout

**Comment by askibinski** [comment] 2015-06-03 07:53
This might be related for this doc: https://github.com/Polymer/core-scaffold/issues/19
(if iron-flex-layout is to replace core-scaffold?)

**Comment by arthurevans** [comment] 2015-06-11 01:05
Duplicate of https://github.com/PolymerElements/iron-flex-layout/issues/16

**Closed by arthurevans** 2015-06-11 01:05 UTC

**Comment by arthurevans** [comment] 2015-06-11 01:08
@askibinski `iron-flex-layout` isn't really related to `core-scaffold`; it's the replacement for the layout attributes used in 0.5: https://www.polymer-project.org/1.0/docs/migration.html#layout-attributes

There's no direct replacement for `core-scaffold`, but the app layout templates are probably the closest thing: https://github.com/PolymerElements/app-layout-templates ... A set of scaffold templates you can copy, instead of a single element you have to kind of work around.

**Comment by askibinski** [comment] 2015-06-11 07:10
Thanks, yes the templates are great to get some examples. It would be worth mentioning these in the migration guide or styling documentation.

**Comment by ssiano** [comment] 2015-06-19 03:53
I don't think this should be closed.  Following is the link that @devmao provided:

https://elements.polymer-project.org/elements/iron-flex-layout

The page at this link still says "No documentation found."
